# Generated by Django 4.2.8 on 2024-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpickups",
            name="status_of_image_processing",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing..."),
                    ("Success", "Success"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
