# Generated by Django 4.2.8 on 2024-01-31 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_globalpickups_status_of_image_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bulk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="status_of_image_processing",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing..."),
                    ("Success", "Success"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="products/%Y/%m/%d"
            ),
            preserve_default=False,
        ),
    ]
