# Generated by Django 4.2.8 on 2024-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_bulk_product_status_of_image_processing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryoption",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("SELECT", "Select"),
                    ("RADIO", "Radio"),
                    ("MULTIPLE_SELECT", "Multiple select"),
                    ("BOOLEAN", "Boolean"),
                ],
                default="SELECT",
                max_length=15,
            ),
        ),
    ]
