# Generated by Django 4.2.8 on 2024-02-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productfile_status_of_image_processing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryoption",
            name="default_values",
            field=models.TextField(blank=True, null=True),
        ),
    ]
