# Generated by Django 4.2.8 on 2024-02-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_product_limited_stock_alter_product_in_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossVariationQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_stock", models.IntegerField()),
                (
                    "variation_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantities",
                        to="products.variationcategory",
                    ),
                ),
                (
                    "variations",
                    models.ManyToManyField(
                        related_name="quantities", to="products.variation"
                    ),
                ),
            ],
        ),
    ]
