# Generated by Django 4.2.8 on 2024-02-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_crossvariationquantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossVariationQuantityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_stock", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_quantities",
                        to="products.product",
                    ),
                ),
                (
                    "variations",
                    models.ManyToManyField(
                        related_name="quantities", to="products.variation"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CrossVariationQuantity",
        ),
    ]
