# Generated by Django 4.2.8 on 2024-02-02 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_crossvariationquantitytable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="in_stock",
        ),
    ]
