# Generated by Django 4.2.8 on 2024-02-02 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_quantity_sold_addressbook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addressbook",
            name="address_type",
        ),
    ]
