# Generated by Django 4.2.8 on 2024-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_product_is_free_shipping_shippingoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="related_images",
            field=models.ManyToManyField(
                blank=True, related_name="variations", to="products.productfile"
            ),
        ),
    ]
