# Generated by Django 4.2.8 on 2024-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_variation_related_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_free_shipping",
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="delivery_days_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="delivery_days_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="is_talkative_price",
            field=models.BooleanField(default=False),
        ),
    ]
