# Generated by Django 4.2.8 on 2024-02-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_remove_product_is_free_shipping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="item_weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="item_width",
            field=models.IntegerField(default=0),
        ),
    ]
