# Generated by Django 4.2.8 on 2024-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_product_item_height_product_item_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hs_code",
            field=models.CharField(default=847130, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="item_length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(default="kg", max_length=20),
        ),
    ]
