# Generated by Django 4.2.8 on 2024-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_product_box_height_product_box_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="units_of_quantity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
