# Generated by Django 4.2.8 on 2024-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_remove_bulkpurchasepolicy_lead_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="box_height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_length",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_width",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_length",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_width",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
