# Generated by Django 4.2.8 on 2024-02-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_alter_product_box_height_alter_product_box_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crossvariationquantitytable",
            name="variations",
        ),
        migrations.AddField(
            model_name="crossvariationquantitytable",
            name="variations",
            field=models.TextField(default="A, A"),
            preserve_default=False,
        ),
    ]
