# Generated by Django 4.2.8 on 2024-02-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_product_created_product_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="shippingoptions",
            old_name="countries",
            new_name="delivery_countries",
        ),
        migrations.RemoveField(
            model_name="shippingoptions",
            name="is_talkative_price",
        ),
        migrations.RemoveField(
            model_name="shippingoptions",
            name="price",
        ),
        migrations.RemoveField(
            model_name="shippingoptions",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shippingoptions",
            name="shipping_type",
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="dimension_calculation",
            field=models.IntegerField(default=1, verbose_name="Cube dimension"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="dimensions_unit",
            field=models.CharField(default="cm", max_length=20),
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="max_dimension",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="max_weight",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="name",
            field=models.CharField(default="Fast", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="origin_countries",
            field=models.TextField(
                default="US", verbose_name="Only country codes with ',' split"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="price_for_dimension",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="price_for_weight",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="product_categories",
            field=models.ManyToManyField(to="products.category"),
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="weight_calculation",
            field=models.IntegerField(default=1, verbose_name="Weight"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoptions",
            name="weight_unit",
            field=models.CharField(default="kg", max_length=20),
        ),
    ]
