# Generated by Django 4.2.8 on 2024-02-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "origin_countries",
                    models.TextField(
                        verbose_name="Origin countries: (only country codes with ',' split)"
                    ),
                ),
                (
                    "delivery_countries",
                    models.TextField(
                        verbose_name="Delivery countries: (only country codes with ',' split)"
                    ),
                ),
                ("delivery_days_min", models.IntegerField()),
                ("delivery_days_max", models.IntegerField()),
                (
                    "price_for_dimension",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Meter cube price"
                    ),
                ),
                (
                    "price_for_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Kilogram price"
                    ),
                ),
                ("max_weight", models.IntegerField(verbose_name="Max meter cube")),
                ("max_dimension", models.IntegerField(verbose_name="Max kilogram")),
                ("product_categories", models.ManyToManyField(to="products.category")),
            ],
        ),
        migrations.DeleteModel(
            name="ShippingOptions",
        ),
    ]
