# Generated by Django 4.2.8 on 2024-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0027_rename_delivery_days_max_shippingoption_max_delivery_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="product_default.png", upload_to="products/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_order_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
