# Generated by Django 4.2.8 on 2024-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_alter_product_image_alter_product_min_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoptions",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
