# Generated by Django 4.2.8 on 2024-02-23 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_address_seller_address_user_and_more"),
        ("products", "0029_productoptions_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addressbook",
            name="user",
        ),
        migrations.DeleteModel(
            name="GlobalPickups",
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.address",
            ),
        ),
        migrations.DeleteModel(
            name="AddressBook",
        ),
    ]
