# Generated by Django 4.2.8 on 2024-02-24 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_remove_addressbook_user_delete_globalpickups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryoption",
            name="field_type",
        ),
    ]
