# Generated by Django 4.2.8 on 2024-02-24 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_remove_categoryoption_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="units_of_quantity",
        ),
    ]
