# Generated by Django 4.2.8 on 2024-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_remove_category_units_of_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default="product_default.png", upload_to="category_images/"
            ),
        ),
    ]
