# Generated by Django 4.2.8 on 2024-03-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_orderitemstatuschangehistory_change_time"),
        ("products", "0034_review_order_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="order_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review",
                to="order.orderitem",
            ),
        ),
    ]
