# Generated by Django 4.2.8 on 2024-03-15 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0035_alter_review_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="country",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="subject",
            field=models.CharField(default="Good", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="username",
            field=models.CharField(default="Amanda", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
