# Generated by Django 4.2.8 on 2024-03-23 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_review_country_review_subject_review_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
