# Generated by Django 4.2.8 on 2024-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_product_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingoption",
            options={
                "verbose_name": "Shipping",
                "verbose_name_plural": "YuuSell Shippings",
            },
        ),
    ]
