# Generated by Django 4.2.8 on 2024-03-30 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_identificationdocument_options_and_more"),
        ("order", "0022_alter_order_options_alter_orderitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0038_alter_product_options_alter_shippingoption_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkpurchasepolicy",
            options={
                "verbose_name": "Bulk purchase policy",
                "verbose_name_plural": "Bulk purchase policies",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="categoryoption",
            options={
                "verbose_name": "Category option",
                "verbose_name_plural": "Category options",
            },
        ),
        migrations.AlterModelOptions(
            name="crossvariationquantitytable",
            options={
                "verbose_name": "Variation quantity",
                "verbose_name_plural": "Variation quantities",
            },
        ),
        migrations.AlterModelOptions(
            name="productfile",
            options={
                "verbose_name": "Product file",
                "verbose_name_plural": "Product files",
            },
        ),
        migrations.AlterModelOptions(
            name="productoptions",
            options={
                "verbose_name": "Product option",
                "verbose_name_plural": "Product options",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="variation",
            options={
                "verbose_name": "Product variation",
                "verbose_name_plural": "Product variations",
            },
        ),
        migrations.AlterModelOptions(
            name="variationcategory",
            options={
                "verbose_name": "Variation category",
                "verbose_name_plural": "Variation categories",
            },
        ),
        migrations.AlterField(
            model_name="bulkpurchasepolicy",
            name="max_lead_time",
            field=models.IntegerField(default=1, verbose_name="Lead time max:"),
        ),
        migrations.AlterField(
            model_name="bulkpurchasepolicy",
            name="min_lead_time",
            field=models.IntegerField(default=1, verbose_name="Lead time min:"),
        ),
        migrations.AlterField(
            model_name="bulkpurchasepolicy",
            name="minimum_quantity",
            field=models.IntegerField(verbose_name="Minimum quantity"),
        ),
        migrations.AlterField(
            model_name="bulkpurchasepolicy",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="bulkpurchasepolicy",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulks",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="hs_code",
            field=models.CharField(max_length=10, verbose_name="HS CODE"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product_default.png",
                upload_to="category_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childrens",
                to="products.category",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="status_of_image_processing",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing..."),
                    ("Success", "Success"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=10,
                verbose_name="Status of image",
            ),
        ),
        migrations.AlterField(
            model_name="categoryoption",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryoption",
            name="default_values",
            field=models.TextField(
                blank=True, null=True, verbose_name="Default values"
            ),
        ),
        migrations.AlterField(
            model_name="categoryoption",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="crossvariationquantitytable",
            name="in_stock",
            field=models.IntegerField(blank=True, null=True, verbose_name="In stock"),
        ),
        migrations.AlterField(
            model_name="crossvariationquantitytable",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation_quantities",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="crossvariationquantitytable",
            name="variations",
            field=models.TextField(verbose_name="Variations"),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="One box height"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="One box length"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="One box weight"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="box_width",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="One box width"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="bulk",
            field=models.BooleanField(default=False, verbose_name="Bulk"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(max_length=255, verbose_name="Country of origin"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="dimensions_unit",
            field=models.CharField(
                default="cm", max_length=20, verbose_name="Dimension unit"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="product_default.png",
                upload_to="products/%Y/%m/%d",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="In stock"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Item weight"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Item length"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Item weight"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_width",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Item width"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_sold_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last sold at"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="limited_stock",
            field=models.BooleanField(default=False, verbose_name="Limited stock"),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Maximum price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_order_quantity",
            field=models.IntegerField(default=1, verbose_name="Minimum quantity"),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Minimum price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_sold",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Sold quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.address",
                verbose_name="Shipping address",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status_of_image_processing",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing..."),
                    ("Success", "Success"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=10,
                verbose_name="Status of image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_of_measuring",
            field=models.CharField(
                default="Count", max_length=255, verbose_name="Unit of measuring"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_unit",
            field=models.CharField(
                default="kg", max_length=20, verbose_name="Weight unit"
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file",
            field=models.FileField(upload_to="product_files/", verbose_name="File"),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="file_type",
            field=models.CharField(
                choices=[("IMAGE", "Image"), ("VIDEO", "Video")],
                default="IMAGE",
                max_length=255,
                verbose_name="File type",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productfile",
            name="status_of_image_processing",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing..."),
                    ("Success", "Success"),
                    ("Error", "Error"),
                ],
                default="Pending",
                max_length=10,
                verbose_name="Status of image",
            ),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="category_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.categoryoption",
                verbose_name="Category option",
            ),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productoptions",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="review",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="review",
            name="order_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review",
                to="order.orderitem",
                verbose_name="Order item",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, max_digits=3, verbose_name="Rating"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="username",
            field=models.CharField(max_length=255, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="max_delivery_time",
            field=models.IntegerField(verbose_name="Maximum delivery time"),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="min_delivery_time",
            field=models.IntegerField(verbose_name="Minimum delivery time"),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="shippingoption",
            name="product_categories",
            field=models.ManyToManyField(
                to="products.category", verbose_name="Categories"
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="products.variationcategory",
                verbose_name="Variation category",
            ),
        ),
        migrations.AlterField(
            model_name="variationcategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="variationcategory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variation_categories",
                to="products.product",
                verbose_name="Product",
            ),
        ),
    ]
