# Generated by Django 4.2.8 on 2024-04-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0039_alter_bulkpurchasepolicy_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkpurchasepolicy",
            name="container_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Container height",
            ),
        ),
        migrations.AddField(
            model_name="bulkpurchasepolicy",
            name="container_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Container length",
            ),
        ),
        migrations.AddField(
            model_name="bulkpurchasepolicy",
            name="container_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bulkpurchasepolicy",
            name="container_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Container weight",
            ),
        ),
        migrations.AddField(
            model_name="bulkpurchasepolicy",
            name="container_width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Container width",
            ),
        ),
    ]
