# Generated by Django 4.2.8 on 2024-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_bulkpurchasepolicy_container_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sell_in_containers",
            field=models.BooleanField(default=False),
        ),
    ]
