# Generated by Django 4.2.8 on 2024-06-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0041_product_sell_in_containers"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="product_default.png",
                        upload_to="sliders/",
                        verbose_name="Image",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.TextField()),
                ("is_mobile", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Slider Image",
                "verbose_name_plural": "Slider Images",
            },
        ),
    ]
