# Generated by Django 4.2.8 on 2024-02-16 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0028_alter_product_image_alter_product_min_order_quantity"),
        ("users", "0006_useraccount_created_at_useraccount_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_shipping_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_item_amount", models.IntegerField()),
                ("status", models.CharField(default="pending", max_length=50)),
                ("destination_full_name", models.CharField(max_length=255)),
                ("destination_address_line1", models.CharField(max_length=255)),
                (
                    "destination_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("destination_city", models.CharField(max_length=100)),
                ("destination_state", models.CharField(max_length=100)),
                ("destination_zip_code", models.CharField(max_length=20)),
                ("destination_country", models.CharField(max_length=100)),
                ("destination_phone_number", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_courier_id", models.CharField(max_length=255)),
                ("shipping_courier_name", models.CharField(max_length=255)),
                (
                    "shipping_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Ship total",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Total",
                    ),
                ),
                ("variations", models.TextField()),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        default="product_default.png",
                        upload_to="order-items/%Y/%m/%d",
                    ),
                ),
                ("bulk", models.BooleanField(default=True)),
                ("origin_address_line1", models.CharField(max_length=255)),
                (
                    "origin_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("origin_city", models.CharField(max_length=100)),
                ("origin_state", models.CharField(max_length=100)),
                ("origin_zip_code", models.CharField(max_length=20)),
                ("origin_country", models.CharField(max_length=100)),
                ("order_notes", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orderitems",
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
