# Generated by Django 4.2.8 on 2024-02-16 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_image",
        ),
    ]
