# Generated by Django 4.2.8 on 2024-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_orderitem_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In Warehouse"),
                    ("DELIVERING", "Delivering"),
                    ("DELIVERED", "Delivered"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
    ]
