# Generated by Django 4.2.8 on 2024-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_order_status_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivered_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="released_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
