# Generated by Django 4.2.8 on 2024-02-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_orderitem_delivered_time_orderitem_released_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wholestore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
