# Generated by Django 4.2.8 on 2024-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_wholestore_alter_orderitem_variations"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RECIEVED", "Recieved"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
