# Generated by Django 4.2.8 on 2024-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_orderitem_process_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="process_status",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("RETURNED_BACK", "Returned back"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
    ]
