# Generated by Django 4.2.8 on 2024-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_orderitem_labels_is_created_orderitem_labels_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippinglabel",
            name="courier_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="courier_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="label_state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document_format",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document_size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="tracking",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="tracking_page_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
