# Generated by Django 4.2.8 on 2024-03-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_shippinglabel_courier_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItemBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.CharField(max_length=255)),
                ("width", models.CharField(max_length=255)),
                ("weight", models.CharField(max_length=255)),
                ("height", models.CharField(max_length=255)),
                ("dimension_unit", models.CharField(max_length=255)),
                ("weight_unit", models.CharField(max_length=255)),
                ("items_amount", models.CharField(max_length=255)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
    ]
