# Generated by Django 4.2.8 on 2024-03-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_orderitembox"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippinglabel",
            name="box",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="label",
                to="order.orderitembox",
            ),
        ),
        migrations.AddField(
            model_name="wholestore",
            name="person_name",
            field=models.CharField(default="YuuSell", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="items_amount",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
