# Generated by Django 4.2.8 on 2024-03-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_shippinglabel_box_wholestore_person_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OrderItemStatusChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "before_state",
                    models.CharField(
                        choices=[
                            ("BUYER_PAID", "Buyer Paid"),
                            ("SHIPPED", "Shipped"),
                            ("IN_WHOLESTORE", "In wholestore"),
                            ("DELIVERED", "Delivered"),
                            ("CANCEL_REQUESTED", "Cancel requested"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED_BACK", "Returned back"),
                        ],
                        default="BUYER_PAID",
                        max_length=50,
                    ),
                ),
                (
                    "finished_state",
                    models.CharField(
                        choices=[
                            ("BUYER_PAID", "Buyer Paid"),
                            ("SHIPPED", "Shipped"),
                            ("IN_WHOLESTORE", "In wholestore"),
                            ("DELIVERED", "Delivered"),
                            ("CANCEL_REQUESTED", "Cancel requested"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED_BACK", "Returned back"),
                        ],
                        default="BUYER_PAID",
                        max_length=50,
                    ),
                ),
                ("change_time", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statushistories",
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
    ]
