# Generated by Django 4.2.8 on 2024-03-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_orderitemstatuschangehistory_change_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_state_name",
                    models.TextField(
                        verbose_name="Origin states: (only state codes with ',' split)"
                    ),
                ),
                (
                    "to_state_name",
                    models.TextField(
                        verbose_name="Delivery states: (only state codes with ',' split)"
                    ),
                ),
                ("tax_percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
