# Generated by Django 4.2.8 on 2024-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_statetax"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                max_digits=10,
                verbose_name="Tax rate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_tax_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=10,
                verbose_name="Total of taxes",
            ),
            preserve_default=False,
        ),
    ]
