# Generated by Django 4.2.8 on 2024-03-23 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_orderitem_tax_rate_orderitem_total_tax_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="card_last_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="card_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="square_payment_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_tax_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
