# Generated by Django 4.2.8 on 2024-03-23 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_order_card_id_order_card_last_4_order_card_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
