# Generated by Django 4.2.8 on 2024-03-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_useraccount_square_customer_id_usercard"),
        ("order", "0018_alter_order_uuid_alter_orderitem_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="app_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                max_digits=10,
                verbose_name="App Fee (10%)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="without_app_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=10,
                verbose_name="Without app fee",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AppFeeClaims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Without app fee",
                    ),
                ),
                (
                    "orderitem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_fees",
                        to="order.orderitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_fees",
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
