# Generated by Django 4.2.8 on 2024-03-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_orderitem_app_fee_orderitem_without_app_fee_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appfeeclaims",
            options={
                "verbose_name": "App Fee Claim",
                "verbose_name_plural": "App Fee Claims",
            },
        ),
        migrations.AlterModelOptions(
            name="statetax",
            options={"verbose_name": "Tax", "verbose_name_plural": "US States Taxes"},
        ),
        migrations.AddField(
            model_name="order",
            name="card_brand",
            field=models.CharField(default="VISA", max_length=255, null=True),
        ),
    ]
