# Generated by Django 4.2.8 on 2024-03-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_appfeeclaims_options_alter_statetax_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="before_state",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="finished_state",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ShippingLabelStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before_state", models.CharField(max_length=50)),
                ("finished_state", models.CharField(max_length=50)),
                ("change_time", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statushistories",
                        to="order.shippinglabel",
                    ),
                ),
            ],
        ),
    ]
