# Generated by Django 4.2.8 on 2024-03-30 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_alter_product_options_alter_shippingoption_options"),
        ("users", "0016_alter_identificationdocument_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0021_orderitem_closed_alter_orderitem_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitembox",
            options={"verbose_name": "Box", "verbose_name_plural": "Boxes"},
        ),
        migrations.AlterModelOptions(
            name="orderitemstatuschangehistory",
            options={
                "verbose_name": "Order item status change history",
                "verbose_name_plural": "Order item status change histories",
            },
        ),
        migrations.AlterModelOptions(
            name="shippinglabel",
            options={"verbose_name": "Label", "verbose_name_plural": "Labels"},
        ),
        migrations.AlterModelOptions(
            name="shippinglabelstatehistory",
            options={
                "verbose_name": "Label history",
                "verbose_name_plural": "Label histories",
            },
        ),
        migrations.AlterModelOptions(
            name="wholestore",
            options={
                "verbose_name": "Wholestore",
                "verbose_name_plural": "Wholestores",
            },
        ),
        migrations.AlterField(
            model_name="appfeeclaims",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="appfeeclaims",
            name="orderitem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="app_fees",
                to="order.orderitem",
                verbose_name="Order item",
            ),
        ),
        migrations.AlterField(
            model_name="appfeeclaims",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="app_fees",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="card_brand",
            field=models.CharField(
                default="VISA", max_length=255, null=True, verbose_name="Card brand"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="card_id",
            field=models.CharField(max_length=255, null=True, verbose_name="Card id"),
        ),
        migrations.AlterField(
            model_name="order",
            name="card_last_4",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Card last 4 digits"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="card_type",
            field=models.CharField(max_length=255, null=True, verbose_name="Card type"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_address_line1",
            field=models.CharField(
                max_length=255, verbose_name="Destination - address line"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_address_line2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Destination - address line 2",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_city",
            field=models.CharField(max_length=100, verbose_name="Destination - city"),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_country",
            field=models.CharField(
                max_length=100, verbose_name="Destination - country"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_full_name",
            field=models.CharField(
                max_length=255, verbose_name="Destination - full name"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_phone_number",
            field=models.CharField(
                max_length=20, verbose_name="Destination - phone number"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_state",
            field=models.CharField(max_length=100, verbose_name="Destination - state"),
        ),
        migrations.AlterField(
            model_name="order",
            name="destination_zip_code",
            field=models.CharField(
                max_length=20, verbose_name="Destination - zip code"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="square_payment_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Square payment id"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_item_amount",
            field=models.IntegerField(verbose_name="Total items"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_shipping_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total shipping",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_tax_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total tax"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="order",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="bulk",
            field=models.BooleanField(default=True, verbose_name="Is bulk"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="closed",
            field=models.BooleanField(default=False, verbose_name="Is closed"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="delivered_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivered time"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="labels_is_created",
            field=models.BooleanField(default=False, verbose_name="Is label created"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="labels_state",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("PENDING", "Pending"),
                    ("ERROR", "Error"),
                    ("GENERATED", "Generated"),
                    ("PRINTED", "Printed"),
                ],
                default="NOT_STARTED",
                max_length=50,
                verbose_name="Label state",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Order notes"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_address_line1",
            field=models.CharField(max_length=255, verbose_name="Origin - address 1"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_address_line2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Origin - address 2"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_city",
            field=models.CharField(max_length=100, verbose_name="Origin - city"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_country",
            field=models.CharField(max_length=100, verbose_name="Origin - country"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_state",
            field=models.CharField(max_length=100, verbose_name="Origin - state"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="origin_zip_code",
            field=models.CharField(max_length=20, verbose_name="Origin - zip code"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255, verbose_name="Product name"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="released_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Released time"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderitems",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_courier_id",
            field=models.CharField(max_length=255, verbose_name="Courier id"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_courier_name",
            field=models.CharField(max_length=255, verbose_name="Courier name"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_courier_type",
            field=models.CharField(
                choices=[("EASYSHIP", "Easyship"), ("YUUSELL", "YuuSell")],
                default="EASYSHIP",
                max_length=50,
                verbose_name="Courier type",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="shipping_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                verbose_name="Shipping total",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, verbose_name="Total price"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variations",
            field=models.TextField(blank=True, null=True, verbose_name="Variations"),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="dimension_unit",
            field=models.CharField(max_length=255, verbose_name="Dimension unit"),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Height"
            ),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="items_amount",
            field=models.IntegerField(default=1, verbose_name="Total items"),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Length"
            ),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="order.orderitem",
                verbose_name="Is label created",
            ),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Weight"
            ),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="weight_unit",
            field=models.CharField(max_length=255, verbose_name="Weight unit"),
        ),
        migrations.AlterField(
            model_name="orderitembox",
            name="width",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Width"
            ),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="before_state",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
                verbose_name="Before state",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="change_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Changed time"),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="finished_state",
            field=models.CharField(
                choices=[
                    ("BUYER_PAID", "Buyer Paid"),
                    ("SHIPPED", "Shipped"),
                    ("IN_WHOLESTORE", "In wholestore"),
                    ("DELIVERED", "Delivered"),
                    ("CANCEL_REQUESTED", "Cancel requested"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURNED_BACK", "Returned back"),
                    ("FAILED_ATTEMPT", "Failed attempt"),
                ],
                default="BUYER_PAID",
                max_length=50,
                verbose_name="Finished state",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemstatuschangehistory",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statushistories",
                to="order.orderitem",
                verbose_name="Order item",
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="box",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="label",
                to="order.orderitembox",
                verbose_name="Box",
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="courier_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Courier id"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="courier_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Courier name"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="label_state",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Label state"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="order.orderitem",
                verbose_name="Order item",
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipment_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Shipment id"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Shipping document"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document_format",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Document format"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="shipping_document_size",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Document size"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="tracking",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tracking"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabel",
            name="tracking_page_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tracking page url"
            ),
        ),
        migrations.AlterField(
            model_name="shippinglabelstatehistory",
            name="before_state",
            field=models.CharField(max_length=50, verbose_name="Before state"),
        ),
        migrations.AlterField(
            model_name="shippinglabelstatehistory",
            name="change_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Change time"),
        ),
        migrations.AlterField(
            model_name="shippinglabelstatehistory",
            name="finished_state",
            field=models.CharField(max_length=50, verbose_name="End state"),
        ),
        migrations.AlterField(
            model_name="shippinglabelstatehistory",
            name="label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statushistories",
                to="order.shippinglabel",
                verbose_name="Label",
            ),
        ),
        migrations.AlterField(
            model_name="statetax",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Tax %"
            ),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="latitude",
            field=models.FloatField(verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="longitude",
            field=models.FloatField(verbose_name="Longtitude"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="person_name",
            field=models.CharField(max_length=255, verbose_name="Person name"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="state",
            field=models.CharField(max_length=100, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="wholestore",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Zip code"),
        ),
    ]
