# Generated by Django 4.2.8 on 2024-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0023_orderitem_bought_in_containers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appfeeclaims",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appfeeclaims",
            name="paid_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Paid time"),
        ),
    ]
