# Generated by Django 4.2.8 on 2024-04-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_appfeeclaims_paid_appfeeclaims_paid_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End time"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("SUCCESS", "Success"),
                        ],
                        default="SCHEDULED",
                        max_length=50,
                        verbose_name="Pickup state",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancellation Reason"
                    ),
                ),
                (
                    "orderitem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="order.orderitem",
                        verbose_name="Order item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order pickup",
                "verbose_name_plural": "Order pickups",
            },
        ),
        migrations.RemoveField(
            model_name="appfeeclaims",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="appfeeclaims",
            name="paid_time",
        ),
        migrations.CreateModel(
            name="PickupOrderStateChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "before_state",
                    models.CharField(max_length=50, verbose_name="Before state"),
                ),
                (
                    "finished_state",
                    models.CharField(max_length=50, verbose_name="End state"),
                ),
                (
                    "change_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Change time"),
                ),
                (
                    "pickup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statushistories",
                        to="order.pickuporder",
                        verbose_name="Pickup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup history",
                "verbose_name_plural": "Pickup histories",
            },
        ),
    ]
