# Generated by Django 4.2.8 on 2024-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0025_pickuporder_remove_appfeeclaims_paid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pickuporder",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="pickuporder",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="pickuporder",
            name="start_time",
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of pickup"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cancellation Reason or Notes"
            ),
        ),
        migrations.AddField(
            model_name="pickuporderstatechangehistory",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Order state change note"
            ),
        ),
    ]
