# Generated by Django 4.2.8 on 2024-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0027_alter_pickuporder_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pickuporderstatechangehistory",
            options={
                "ordering": ["-change_time"],
                "verbose_name": "Pickup history",
                "verbose_name_plural": "Pickup histories",
            },
        ),
        migrations.RemoveField(
            model_name="pickuporder",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="pickuporderstatechangehistory",
            name="notes",
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_zip_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Zip code"
            ),
        ),
        migrations.AlterField(
            model_name="pickuporder",
            name="state",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("FAILED", "Failed"),
                    ("SUCCESS", "Success"),
                ],
                default="SCHEDULED",
                max_length=50,
                verbose_name="Pickup state",
            ),
        ),
    ]
