# Generated by Django 4.2.8 on 2024-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0028_alter_pickuporderstatechangehistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="pickuporder",
            name="wholestore_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
