# Generated by Django 4.2.8 on 2024-03-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_orderitem_labels_is_created_orderitem_labels_state_and_more"),
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelCreateFail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error", models.TextField()),
                ("notes", models.TextField()),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="label_create_fail",
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
    ]
