# Generated by Django 4.2.8 on 2024-03-08 07:27

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_supportcase"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("client", "Client"), ("seller", "Seller")],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="product_default.png",
                        upload_to="help-categories/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HelpItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("client", "Client"), ("seller", "Seller")],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("short_description", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="product_default.png",
                        upload_to="help-items/",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpitems",
                        to="administration.helpcategory",
                    ),
                ),
            ],
        ),
    ]
