categories_data = [
    {
        "name": "Electronics",
        "hs_code": "8517",
        "image": "category_images/electronics.png",
        "subcategories": [
            {"name": "Smartphones", "hs_code": "851712", "image": "category_images/smartphones.jpg"},
            {"name": "Laptops", "hs_code": "847130", "image": "category_images/laptops.jpg"},
            {"name": "Tablets", "hs_code": "847130", "image": "category_images/tablets.jpg"},
            {"name": "Desktop Computers", "hs_code": "847150", "image": "category_images/desktop_computers.jpg"},
            {"name": "Monitors", "hs_code": "852852", "image": "category_images/monitors.jpg"},
            {"name": "Printers", "hs_code": "844332", "image": "category_images/printers.jpg"},
            {"name": "Cameras", "hs_code": "852580", "image": "category_images/cameras.jpg"},
            {"name": "Headphones", "hs_code": "851830", "image": "category_images/headphones.jpg"},
            {"name": "Speakers", "hs_code": "851821", "image": "category_images/speakers.jpg"},
            {"name": "Smartwatches", "hs_code": "851762", "image": "category_images/smartwatches.jpg"},
            {"name": "Drones", "hs_code": "852691", "image": "category_images/drones.jpg"},
            {"name": "Gaming Consoles", "hs_code": "950450", "image": "category_images/gaming_consoles.jpg"},
            {"name": "VR Headsets", "hs_code": "852990", "image": "category_images/vr_headsets.jpg"},
            {"name": "E-readers", "hs_code": "847130", "image": "category_images/e_readers.jpg"},
            {"name": "External Hard Drives", "hs_code": "847170", "image": "category_images/external_hard_drives.jpg"},
            {"name": "Memory Cards", "hs_code": "852351", "image": "category_images/memory_cards.jpg"},
            {"name": "Network Devices", "hs_code": "851762", "image": "category_images/network_devices.jpg"},
            {"name": "Projectors", "hs_code": "852862", "image": "category_images/projectors.jpg"},
            {"name": "Smart Home Devices", "hs_code": "851769", "image": "category_images/smart_home_devices.jpg"},
            {"name": "Wearable Technology", "hs_code": "851762", "image": "category_images/wearable_technology.jpg"},
        ],
    },
    {
        "name": "Fashion",
        "hs_code": "61",
        "image": "category_images/fashion.png",
        "subcategories": [
            {"name": "Clothing", "hs_code": "611300", "image": "category_images/clothing.jpg"},
            {"name": "Shoes", "hs_code": "6403", "image": "category_images/shoes.jpg"},
            {"name": "Accessories", "hs_code": "6307", "image": "category_images/accessories.jpg"},
            {"name": "Bags", "hs_code": "4202", "image": "category_images/bags.jpg"},
            {"name": "Jewelry", "hs_code": "7113", "image": "category_images/jewelry.jpg"},
            {"name": "Watches", "hs_code": "9102", "image": "category_images/watches.jpg"},
            {"name": "Sunglasses", "hs_code": "9004", "image": "category_images/sunglasses.jpg"},
            {"name": "Hats", "hs_code": "6505", "image": "category_images/hats.jpg"},
            {"name": "Belts", "hs_code": "4203", "image": "category_images/belts.jpg"},
            {"name": "Scarves", "hs_code": "6214", "image": "category_images/scarves.jpg"},
            {"name": "Socks", "hs_code": "6115", "image": "category_images/socks.jpg"},
            {"name": "Underwear", "hs_code": "6212", "image": "category_images/underwear.jpg"},
            {"name": "Swimwear", "hs_code": "6112", "image": "category_images/swimwear.jpg"},
            {"name": "Formal Wear", "hs_code": "6203", "image": "category_images/formal_wear.jpg"},
            {"name": "Sportswear", "hs_code": "6112", "image": "category_images/sportswear.jpg"},
            {"name": "Sleepwear", "hs_code": "6208", "image": "category_images/sleepwear.jpg"},
            {"name": "Maternity Wear", "hs_code": "6202", "image": "category_images/maternity_wear.jpg"},
            {"name": "Ethnic Wear", "hs_code": "6204", "image": "category_images/ethnic_wear.jpg"},
            {"name": "Costumes", "hs_code": "6203", "image": "category_images/costumes.jpg"},
            {"name": "Plus Size Clothing", "hs_code": "6203", "image": "category_images/plus_size_clothing.jpg"},
        ],
    },
    {
        "name": "Home & Garden",
        "hs_code": "9403",
        "image": "category_images/home_garden.png",
        "subcategories": [
            {"name": "Furniture", "hs_code": "940360", "image": "category_images/furniture.jpg"},
            {"name": "Kitchenware", "hs_code": "392410", "image": "category_images/kitchenware.jpg"},
            {"name": "Gardening", "hs_code": "8201", "image": "category_images/gardening.jpg"},
            {"name": "Home Decor", "hs_code": "940490", "image": "category_images/home_decor.jpg"},
            {"name": "Bedding", "hs_code": "9404", "image": "category_images/bedding.jpg"},
            {"name": "Bathroom Accessories", "hs_code": "3922", "image": "category_images/bathroom_accessories.jpg"},
            {"name": "Lighting", "hs_code": "9405", "image": "category_images/lighting.jpg"},
            {"name": "Outdoor Furniture", "hs_code": "9401", "image": "category_images/outdoor_furniture.jpg"},
            {"name": "Tools", "hs_code": "8206", "image": "category_images/tools.jpg"},
            {"name": "Home Improvement", "hs_code": "8302", "image": "category_images/home_improvement.jpg"},
            {"name": "Storage & Organization", "hs_code": "9403", "image": "category_images/storage_organization.jpg"},
            {"name": "Pet Supplies", "hs_code": "4201", "image": "category_images/pet_supplies.jpg"},
            {"name": "Plants", "hs_code": "0602", "image": "category_images/plants.jpg"},
            {"name": "Pools & Spas", "hs_code": "9506", "image": "category_images/pools_spas.jpg"},
            {"name": "Pest Control", "hs_code": "3808", "image": "category_images/pest_control.jpg"},
            {"name": "Seasonal Decor", "hs_code": "9505", "image": "category_images/seasonal_decor.jpg"},
            {"name": "Cleaning Supplies", "hs_code": "3402", "image": "category_images/cleaning_supplies.jpg"},
            {"name": "Safety & Security", "hs_code": "8301", "image": "category_images/safety_security.jpg"},
            {"name": "Home Appliances", "hs_code": "8509", "image": "category_images/home_appliances.jpg"},
            {"name": "Barbecue & Outdoor Cooking", "hs_code": "7321", "image": "category_images/barbecue_outdoor_cooking.jpg"},
        ],
    },
     {
        "name": "Sports & Outdoors",
        "hs_code": "9506",
        "image": "category_images/sports_outdoors.jpg",
        "subcategories": [
            {"name": "Fitness Equipment", "hs_code": "950691", "image": "category_images/fitness_equipment.jpg"},
            {"name": "Camping Gear", "hs_code": "6306", "image": "category_images/camping_gear.jpg"},
            {"name": "Cycling", "hs_code": "8712", "image": "category_images/cycling.jpg"},
            {"name": "Fishing", "hs_code": "9507", "image": "category_images/fishing.jpg"},
            {"name": "Hiking", "hs_code": "6402", "image": "category_images/hiking.jpg"},
        ],
    },
    {
        "name": "Beauty & Personal Care",
        "hs_code": "3304",
        "image": "category_images/beauty_personal_care.png",
        "subcategories": [
            {"name": "Skincare", "hs_code": "330499", "image": "category_images/skincare.jpg"},
            {"name": "Makeup", "hs_code": "330420", "image": "category_images/makeup.jpg"},
            {"name": "Hair Care", "hs_code": "3305", "image": "category_images/hair_care.jpg"},
            {"name": "Fragrances", "hs_code": "3303", "image": "category_images/fragrances.jpg"},
            {"name": "Personal Hygiene", "hs_code": "9619", "image": "category_images/personal_hygiene.jpg"},
        ],
    },
    {
        "name": "Toys & Games",
        "hs_code": "9503",
        "image": "category_images/toys_games.jpg",
        "subcategories": [
            {"name": "Action Figures", "hs_code": "950300", "image": "category_images/action_figures.jpg"},
            {"name": "Board Games", "hs_code": "950490", "image": "category_images/board_games.jpg"},
            {"name": "Dolls", "hs_code": "950300", "image": "category_images/dolls.jpg"},
            {"name": "Puzzles", "hs_code": "950300", "image": "category_images/puzzles.jpg"},
            {"name": "Outdoor Toys", "hs_code": "950699", "image": "category_images/outdoor_toys.jpg"},
        ],
    },
    {
        "name": "Books & Stationery",
        "hs_code": "4901",
        "image": "category_images/books_stationery.jpg",
        "subcategories": [
            {"name": "Fiction Books", "hs_code": "490199", "image": "category_images/fiction_books.jpg"},
            {"name": "Non-Fiction Books", "hs_code": "490199", "image": "category_images/non_fiction_books.jpg"},
            {"name": "Children's Books", "hs_code": "490300", "image": "category_images/childrens_books.jpg"},
            {"name": "Notebooks", "hs_code": "4820", "image": "category_images/notebooks.jpg"},
            {"name": "Writing Instruments", "hs_code": "9608", "image": "category_images/writing_instruments.jpg"},
        ],
    },
    {
        "name": "Food & Beverage",
        "hs_code": "2106",
        "image": "category_images/food_beverage.jpg",
        "subcategories": [
            {"name": "Snacks", "hs_code": "1905", "image": "category_images/snacks.jpg"},
            {"name": "Beverages", "hs_code": "2202", "image": "category_images/beverages.jpg"},
            {"name": "Gourmet Foods", "hs_code": "2106", "image": "category_images/gourmet_foods.jpg"},
            {"name": "Health Foods", "hs_code": "2106", "image": "category_images/health_foods.jpg"},
            {"name": "Canned & Packaged Foods", "hs_code": "2001", "image": "category_images/canned_packaged_foods.jpg"},
        ],
    },
    {
        "name": "Health & Wellness",
        "hs_code": "3004",
        "image": "category_images/health_wellness.jpg",
        "subcategories": [
            {"name": "Vitamins & Supplements", "hs_code": "2106", "image": "category_images/vitamins_supplements.jpg"},
            {"name": "Personal Care", "hs_code": "3307", "image": "category_images/personal_care.jpg"},
            {"name": "Fitness & Nutrition", "hs_code": "2106", "image": "category_images/fitness_nutrition.jpg"},
            {"name": "Medical Supplies", "hs_code": "9018", "image": "category_images/medical_supplies.jpg"},
            {"name": "Wellness Devices", "hs_code": "9019", "image": "category_images/wellness_devices.jpg"},
        ],
    },
    {
        "name": "Automotive",
        "hs_code": "8703",
        "image": "category_images/automotive.jpg",
        "subcategories": [
            {"name": "Car Accessories", "hs_code": "8708", "image": "category_images/car_accessories.jpg"},
            {"name": "Car Electronics", "hs_code": "8512", "image": "category_images/car_electronics.jpg"},
            {"name": "Car Care", "hs_code": "3405", "image": "category_images/car_care.jpg"},
            {"name": "Motorcycle Parts", "hs_code": "8714", "image": "category_images/motorcycle_parts.jpg"},
            {"name": "Tires & Wheels", "hs_code": "4011", "image": "category_images/tires_wheels.jpg"},
        ],
    },
]


category_options_data = {
    "Smartphones": [
        {"name": "Brand", "default_values": "Apple, Samsung, Xiaomi, Huawei"},
        {"name": "Storage", "default_values": "64GB, 128GB, 256GB, 512GB"},
        {"name": "Color", "default_values": "Black, White, Gold, Blue"},
        {"name": "Operating System", "default_values": "iOS, Android"},
    ],
    "Laptops": [
        {"name": "Brand", "default_values": "Apple, Dell, HP, Lenovo"},
        {"name": "Processor", "default_values": "Intel Core i5, Intel Core i7, AMD Ryzen 5, AMD Ryzen 7"},
        {"name": "RAM", "default_values": "8GB, 16GB, 32GB"},
        {"name": "Storage", "default_values": "256GB SSD, 512GB SSD, 1TB SSD"},
    ],
    "Tablets": [
        {"name": "Brand", "default_values": "Apple, Samsung, Lenovo, Microsoft"},
        {"name": "Screen Size", "default_values": "8 inches, 10 inches, 12 inches"},
        {"name": "Storage", "default_values": "32GB, 64GB, 128GB, 256GB"},
        {"name": "Operating System", "default_values": "iOS, Android, Windows"},
    ],
    "Desktop Computers": [
        {"name": "Brand", "default_values": "Dell, HP, Lenovo, Apple"},
        {"name": "Processor", "default_values": "Intel Core i5, Intel Core i7, AMD Ryzen 5, AMD Ryzen 7"},
        {"name": "RAM", "default_values": "8GB, 16GB, 32GB"},
        {"name": "Storage", "default_values": "1TB HDD, 256GB SSD, 512GB SSD"},
    ],
    "Monitors": [
        {"name": "Brand", "default_values": "Samsung, LG, Dell, Acer"},
        {"name": "Screen Size", "default_values": "24 inches, 27 inches, 32 inches"},
        {"name": "Resolution", "default_values": "1080p, 1440p, 4K"},
        {"name": "Refresh Rate", "default_values": "60Hz, 144Hz, 240Hz"},
    ],
    "Printers": [
        {"name": "Brand", "default_values": "HP, Canon, Epson, Brother"},
        {"name": "Type", "default_values": "Inkjet, Laser, All-in-One"},
        {"name": "Connectivity", "default_values": "USB, Wi-Fi, Ethernet"},
        {"name": "Color", "default_values": "Monochrome, Color"},
    ],
    "Cameras": [
        {"name": "Brand", "default_values": "Canon, Nikon, Sony, Panasonic"},
        {"name": "Type", "default_values": "DSLR, Mirrorless, Compact"},
        {"name": "Resolution", "default_values": "24MP, 36MP, 42MP"},
        {"name": "Lens", "default_values": "Wide Angle, Telephoto, Zoom, Prime"},
    ],
    "Headphones": [
        {"name": "Brand", "default_values": "Sony, Bose, Sennheiser, Beats"},
        {"name": "Type", "default_values": "In-Ear, On-Ear, Over-Ear"},
        {"name": "Connectivity", "default_values": "Wired, Wireless, Bluetooth"},
        {"name": "Noise Cancellation", "default_values": "Active, Passive"},
    ],
    "Speakers": [
        {"name": "Brand", "default_values": "JBL, Bose, Sony, Sonos"},
        {"name": "Type", "default_values": "Portable, Bookshelf, Soundbar, Floor-Standing"},
        {"name": "Connectivity", "default_values": "Wired, Wireless, Bluetooth"},
        {"name": "Water Resistance", "default_values": "Yes, No"},
    ],
    "Smartwatches": [
        {"name": "Brand", "default_values": "Apple, Samsung, Garmin, Fitbit"},
        {"name": "Compatibility", "default_values": "iOS, Android"},
        {"name": "Features", "default_values": "Heart Rate Monitor, GPS, Waterproof, Music Playback"},
        {"name": "Battery Life", "default_values": "Up to 1 day, Up to 2 days, Up to 5 days"},
    ],
    "Drones": [
        {"name": "Brand", "default_values": "DJI, Parrot, Yuneec, Autel Robotics"},
        {"name": "Camera Resolution", "default_values": "12MP, 20MP, 48MP"},
        {"name": "Flight Time", "default_values": "Up to 20 minutes, Up to 30 minutes, Up to 40 minutes"},
        {"name": "Range", "default_values": "Up to 1 km, Up to 5 km, Up to 10 km"},
    ],
    "Gaming Consoles": [
        {"name": "Brand", "default_values": "Sony, Microsoft, Nintendo, Sega"},
        {"name": "Type", "default_values": "Home Console, Handheld, Hybrid"},
        {"name": "Storage", "default_values": "500GB, 1TB, 2TB"},
        {"name": "Compatibility", "default_values": "Physical Discs, Digital Downloads, Backward Compatible"},
    ],
    "VR Headsets": [
        {"name": "Brand", "default_values": "Oculus, HTC, Valve, Sony"},
        {"name": "Resolution", "default_values": "1080x1200 per eye, 1440x1600 per eye, 1832x1920 per eye"},
        {"name": "Field of View", "default_values": "90 degrees, 110 degrees, 120 degrees"},
        {"name": "Tracking", "default_values": "3DOF, 6DOF, Inside-Out, External Sensors"},
    ],
    "E-readers": [
        {"name": "Brand", "default_values": "Amazon Kindle, Kobo, Barnes & Noble Nook, Onyx Boox"},
        {"name": "Screen Size", "default_values": "6 inches, 7 inches, 8 inches, 10 inches"},
        {"name": "Storage", "default_values": "4GB, 8GB, 32GB"},
        {"name": "Connectivity", "default_values": "Wi-Fi, Wi-Fi + Cellular"},
    ],
    "External Hard Drives": [
        {"name": "Brand", "default_values": "Seagate, Western Digital, Toshiba, LaCie"},
        {"name": "Capacity", "default_values": "1TB, 2TB, 4TB, 8TB"},
        {"name": "Connectivity", "default_values": "USB 3.0, USB-C, Thunderbolt"},
        {"name": "Form Factor", "default_values": "Portable, Desktop"},
    ],
    "Memory Cards": [
        {"name": "Type", "default_values": "SD, microSD, CompactFlash, CFexpress"},
        {"name": "Capacity", "default_values": "32GB, 64GB, 128GB, 256GB"},
        {"name": "Speed Class", "default_values": "Class 10, UHS-I, UHS-II, V90"},
        {"name": "Brand", "default_values": "SanDisk, Lexar, Samsung, Kingston"},
    ],
    "Network Devices": [
        {"name": "Type", "default_values": "Routers, Modems, Switches, Access Points"},
        {"name": "Brand", "default_values": "Netgear, TP-Link, Cisco, Ubiquiti"},
        {"name": "Speed", "default_values": "AC1200, AC1900, AX3000, AX6000"},
        {"name": "Connectivity", "default_values": "Ethernet, Wi-Fi, Dual-Band, Tri-Band"},
    ],
    "Projectors": [
        {"name": "Brand", "default_values": "Epson, BenQ, Optoma, LG"},
        {"name": "Resolution", "default_values": "1080p, 4K, WXGA, XGA"},
        {"name": "Brightness", "default_values": "2000 lumens, 3000 lumens, 4000 lumens"},
        {"name": "Technology", "default_values": "DLP, LCD, LED, Laser"},
    ],
    "Smart Home Devices": [
        {"name": "Type", "default_values": "Smart Speakers, Smart Lights, Smart Thermostats, Smart Locks"},
        {"name": "Brand", "default_values": "Amazon, Google, Philips Hue, Nest"},
        {"name": "Connectivity", "default_values": "Wi-Fi, Bluetooth, Zigbee, Z-Wave"},
        {"name": "Compatibility", "default_values": "Amazon Alexa, Google Assistant, Apple HomeKit"},
    ],
    "Wearable Technology": [
        {"name": "Type", "default_values": "Smartwatches, Fitness Trackers, Smart Glasses, Body Cameras"},
        {"name": "Brand", "default_values": "Apple, Fitbit, Garmin, Samsung"},
        {"name": "Features", "default_values": "Heart Rate Monitor, GPS, Water Resistance, Sleep Tracking"},
        {"name": "Compatibility", "default_values": "iOS, Android"},
    ],
    "Clothing": [
        {"name": "Size", "default_values": "XS, S, M, L, XL, XXL"},
        {"name": "Color", "default_values": "Black, White, Red, Blue, Green"},
        {"name": "Material", "default_values": "Cotton, Polyester, Wool, Silk"},
        {"name": "Style", "default_values": "Casual, Formal, Sporty, Vintage"},
    ],
    "Shoes": [
        {"name": "Size", "default_values": "5, 6, 7, 8, 9, 10, 11, 12"},
        {"name": "Color", "default_values": "Black, White, Brown, Red, Blue"},
        {"name": "Material", "default_values": "Leather, Synthetic, Rubber, Canvas"},
        {"name": "Type", "default_values": "Sneakers, Boots, Sandals, Heels"},
    ],
    "Accessories": [
        {"name": "Type", "default_values": "Belts, Hats, Scarves, Gloves"},
        {"name": "Color", "default_values": "Black, White, Brown, Red, Blue"},
        {"name": "Material", "default_values": "Leather, Cotton, Wool, Silk"},
        {"name": "Style", "default_values": "Casual, Formal, Sporty, Vintage"},
    ],
    "Bags": [
        {"name": "Type", "default_values": "Handbags, Backpacks, Totes, Clutches"},
        {"name": "Color", "default_values": "Black, Brown, Red, Blue, Green"},
        {"name": "Material", "default_values": "Leather, Canvas, Nylon, Polyester"},
        {"name": "Size", "default_values": "Small, Medium, Large, Extra Large"},
    ],
    "Jewelry": [
        {"name": "Type", "default_values": "Necklaces, Earrings, Bracelets, Rings"},
        {"name": "Material", "default_values": "Gold, Silver, Platinum, Stainless Steel"},
        {"name": "Gemstone", "default_values": "Diamond, Ruby, Sapphire, Emerald"},
        {"name": "Style", "default_values": "Classic, Modern, Vintage, Bohemian"},
    ],
    "Watches": [
        {"name": "Brand", "default_values": "Rolex, Omega, Casio, Seiko"},
        {"name": "Material", "default_values": "Stainless Steel, Leather, Gold, Titanium"},
        {"name": "Type", "default_values": "Analog, Digital, Smartwatch, Chronograph"},
        {"name": "Water Resistance", "default_values": "30m, 50m, 100m, 200m"},
    ],
    "Sunglasses": [
        {"name": "Brand", "default_values": "Ray-Ban, Oakley, Gucci, Prada"},
        {"name": "Frame Material", "default_values": "Plastic, Metal, Carbon Fiber, Wood"},
        {"name": "Lens Material", "default_values": "Glass, Polycarbonate, Plastic"},
        {"name": "Style", "default_values": "Aviator, Wayfarer, Round, Square"},
    ],
    "Hats": [
        {"name": "Type", "default_values": "Baseball Cap, Fedora, Beanie, Panama"},
        {"name": "Material", "default_values": "Cotton, Wool, Straw, Leather"},
        {"name": "Size", "default_values": "Small, Medium, Large, Extra Large"},
        {"name": "Color", "default_values": "Black, White, Brown, Blue"},
    ],
    "Belts": [
        {"name": "Material", "default_values": "Leather, Synthetic, Fabric"},
        {"name": "Color", "default_values": "Black, Brown, Tan, White"},
        {"name": "Size", "default_values": "Small, Medium, Large, Extra Large"},
        {"name": "Buckle Type", "default_values": "Pin Buckle, Plate Buckle, Automatic Buckle"},
    ],
    "Scarves": [
        {"name": "Material", "default_values": "Silk, Cotton, Wool, Cashmere"},
        {"name": "Color", "default_values": "Red, Blue, Green, Yellow, Black"},
        {"name": "Pattern", "default_values": "Solid, Striped, Plaid, Floral"},
        {"name": "Size", "default_values": "Small, Medium, Large"},
    ],
    "Socks": [
        {"name": "Material", "default_values": "Cotton, Wool, Bamboo, Synthetic"},
        {"name": "Size", "default_values": "Small, Medium, Large, Extra Large"},
        {"name": "Type", "default_values": "Ankle, Crew, Knee-High, No-Show"},
        {"name": "Color", "default_values": "Black, White, Grey, Blue"},
    ],
    "Underwear": [
        {"name": "Type", "default_values": "Briefs, Boxers, Trunks, Thongs"},
        {"name": "Material", "default_values": "Cotton, Modal, Microfiber, Silk"},
        {"name": "Size", "default_values": "Small, Medium, Large, Extra Large"},
        {"name": "Color", "default_values": "Black, White, Grey, Blue"},
    ],
    "Swimwear": [
        {"name": "Type", "default_values": "Bikini, One-Piece, Swim Trunks, Board Shorts"},
        {"name": "Material", "default_values": "Polyester, Nylon, Spandex, Neoprene"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Color", "default_values": "Black, Blue, Red, Green"},
    ],
    "Formal Wear": [
        {"name": "Type", "default_values": "Suits, Tuxedos, Dress Shirts, Evening Gowns"},
        {"name": "Material", "default_values": "Wool, Silk, Cotton, Polyester"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Color", "default_values": "Black, Navy, Grey, White"},
    ],
    "Sportswear": [
        {"name": "Type", "default_values": "T-Shirts, Shorts, Leggings, Sports Bras"},
        {"name": "Material", "default_values": "Polyester, Nylon, Spandex, Cotton"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Color", "default_values": "Black, White, Blue, Red"},
    ],
    "Sleepwear": [
        {"name": "Type", "default_values": "Pajamas, Nightgowns, Robes, Sleep Shorts"},
        {"name": "Material", "default_values": "Cotton, Silk, Satin, Fleece"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Color", "default_values": "Blue, Pink, White, Grey"},
    ],
    "Maternity Wear": [
        {"name": "Type", "default_values": "Dresses, Tops, Pants, Nursing Wear"},
        {"name": "Material", "default_values": "Cotton, Spandex, Modal, Rayon"},
        {"name": "Size", "default_values": "S, M, L, XL, XXL"},
        {"name": "Color", "default_values": "Black, Navy, Grey, Pink"},
    ],
    "Ethnic Wear": [
        {"name": "Type", "default_values": "Sarees, Kurtas, Lehengas, Sherwanis"},
        {"name": "Material", "default_values": "Silk, Cotton, Georgette, Chiffon"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Color", "default_values": "Red, Blue, Green, Yellow"},
    ],
    "Costumes": [
        {"name": "Type", "default_values": "Halloween, Cosplay, Historical, Mascot"},
        {"name": "Material", "default_values": "Polyester, Cotton, Latex, Foam"},
        {"name": "Size", "default_values": "XS, S, M, L, XL"},
        {"name": "Theme", "default_values": "Superheroes, Fantasy, Sci-Fi, Animals"},
    ],
    "Plus Size Clothing": [
        {"name": "Type", "default_values": "Dresses, Tops, Pants, Outerwear"},
        {"name": "Material", "default_values": "Cotton, Polyester, Spandex, Rayon"},
        {"name": "Size", "default_values": "XL, XXL, 3XL, 4XL, 5XL"},
        {"name": "Color", "default_values": "Black, Navy, White, Red"},
    ],
    "Furniture": [
        {"name": "Type", "default_values": "Sofas, Chairs, Tables, Beds"},
        {"name": "Material", "default_values": "Wood, Metal, Plastic, Fabric"},
        {"name": "Style", "default_values": "Modern, Traditional, Industrial, Rustic"},
        {"name": "Room", "default_values": "Living Room, Bedroom, Dining Room, Office"},
    ],
    "Kitchenware": [
        {"name": "Type", "default_values": "Cookware, Bakeware, Utensils, Cutlery"},
        {"name": "Material", "default_values": "Stainless Steel, Aluminum, Silicone, Glass"},
        {"name": "Brand", "default_values": "T-fal, Cuisinart, KitchenAid, Calphalon"},
        {"name": "Features", "default_values": "Non-Stick, Dishwasher Safe, Oven Safe, Microwave Safe"},
    ],
    "Gardening": [
        {"name": "Type", "default_values": "Tools, Planters, Soil, Fertilizers"},
        {"name": "Plants", "default_values": "Flowers, Vegetables, Herbs, Shrubs"},
        {"name": "Accessories", "default_values": "Gloves, Watering Cans, Hoses, Sprinklers"},
        {"name": "Brand", "default_values": "Fiskars, Scotts, Miracle-Gro, Gardena"},
    ],
    "Home Decor": [
        {"name": "Type", "default_values": "Candles, Vases, Wall Art, Mirrors"},
        {"name": "Style", "default_values": "Contemporary, Vintage, Bohemian, Minimalist"},
        {"name": "Color", "default_values": "Blue, Green, Red, Yellow"},
        {"name": "Material", "default_values": "Glass, Metal, Wood, Ceramic"},
    ],
    "Bedding": [
        {"name": "Type", "default_values": "Sheets, Comforters, Pillows, Duvet Covers"},
        {"name": "Material", "default_values": "Cotton, Polyester, Silk, Linen"},
        {"name": "Size", "default_values": "Twin, Full, Queen, King"},
        {"name": "Brand", "default_values": "Brooklinen, Casper, Parachute, Boll & Branch"},
    ],
    "Bathroom Accessories": [
        {"name": "Type", "default_values": "Towels, Shower Curtains, Bath Mats, Soap Dispensers"},
        {"name": "Material", "default_values": "Cotton, Polyester, Ceramic, Plastic"},
        {"name": "Color", "default_values": "White, Blue, Grey, Beige"},
        {"name": "Brand", "default_values": "Moen, Delta, Kohler, American Standard"},
    ],
    "Lighting": [
        {"name": "Type", "default_values": "Table Lamps, Floor Lamps, Ceiling Lights, Wall Lights"},
        {"name": "Style", "default_values": "Modern, Industrial, Traditional, Rustic"},
        {"name": "Material", "default_values": "Metal, Glass, Wood, Plastic"},
        {"name": "Features", "default_values": "LED, Dimmable, Energy Efficient, Smart"},
    ],
    "Outdoor Furniture": [
        {"name": "Type", "default_values": "Patio Sets, Hammocks, Outdoor Chairs, Outdoor Tables"},
        {"name": "Material", "default_values": "Wicker, Metal, Wood, Plastic"},
        {"name": "Brand", "default_values": "Hampton Bay, Trex, Sunbrella, Keter"},
        {"name": "Features", "default_values": "Weather-Resistant, UV Protected, Foldable, Adjustable"},
    ],
    "Tools": [
        {"name": "Type", "default_values": "Hand Tools, Power Tools, Gardening Tools, Measuring Tools"},
        {"name": "Brand", "default_values": "DeWalt, Bosch, Milwaukee, Makita"},
        {"name": "Purpose", "default_values": "Drilling, Cutting, Sanding, Fastening"},
        {"name": "Features", "default_values": "Cordless, Battery-Powered, Ergonomic Design, Durable"},
    ],
    "Home Improvement": [
        {"name": "Type", "default_values": "Paint, Hardware, Electrical, Plumbing"},
        {"name": "Brand", "default_values": "Behr, Schlage, Leviton, Moen"},
        {"name": "Project", "default_values": "Renovation, Repair, Decoration, Installation"},
        {"name": "Tools", "default_values": "Drills, Saws, Hammers, Screwdrivers"},
    ],
    "Storage & Organization": [
        {"name": "Type", "default_values": "Shelves, Bins, Closet Organizers, Drawer Organizers"},
        {"name": "Material", "default_values": "Plastic, Metal, Wood, Fabric"},
        {"name": "Room", "default_values": "Kitchen, Bathroom, Bedroom, Garage"},
        {"name": "Features", "default_values": "Stackable, Collapsible, Adjustable, Wall-Mounted"},
    ],
    "Pet Supplies": [
        {"name": "Type", "default_values": "Food, Toys, Beds, Leashes"},
        {"name": "Animal", "default_values": "Dogs, Cats, Birds, Fish"},
        {"name": "Brand", "default_values": "Purina, Kong, PetSafe, Tetra"},
        {"name": "Features", "default_values": "Organic, Hypoallergenic, Durable, Washable"},
    ],
    "Plants": [
        {"name": "Type", "default_values": "Indoor Plants, Outdoor Plants, Succulents, Flowering Plants"},
        {"name": "Care Level", "default_values": "Low Maintenance, Moderate, High Maintenance"},
        {"name": "Light Requirement", "default_values": "Low Light, Medium Light, Bright Light"},
        {"name": "Watering Frequency", "default_values": "Once a Week, Twice a Week, Every Two Weeks"},
    ],
    "Pools & Spas": [
        {"name": "Type", "default_values": "Inground Pools, Above Ground Pools, Hot Tubs, Saunas"},
        {"name": "Material", "default_values": "Vinyl, Fiberglass, Concrete, Acrylic"},
        {"name": "Brand", "default_values": "Intex, Coleman, Jacuzzi, Hayward"},
        {"name": "Features", "default_values": "Heated, Saltwater System, LED Lighting, Jets"},
    ],
    "Pest Control": [
        {"name": "Type", "default_values": "Insecticides, Rodenticides, Traps, Repellents"},
        {"name": "Target Pest", "default_values": "Ants, Mosquitoes, Mice, Rats"},
        {"name": "Form", "default_values": "Spray, Bait, Granules, Ultrasonic"},
        {"name": "Brand", "default_values": "Ortho, Raid, Victor, Tomcat"},
    ],
    "Seasonal Decor": [
        {"name": "Occasion", "default_values": "Christmas, Halloween, Easter, Thanksgiving"},
        {"name": "Type", "default_values": "Ornaments, Lights, Wreaths, Inflatables"},
        {"name": "Material", "default_values": "Plastic, Glass, Metal, Fabric"},
        {"name": "Theme", "default_values": "Traditional, Modern, Whimsical, Rustic"},
    ],
    "Cleaning Supplies": [
        {"name": "Type", "default_values": "Detergents, Disinfectants, Sponges, Mops"},
        {"name": "Brand", "default_values": "Clorox, Lysol, Mr. Clean, Swiffer"},
        {"name": "Surface", "default_values": "Floors, Countertops, Windows, Bathroom"},
        {"name": "Features", "default_values": "Eco-Friendly, Antibacterial, Non-Toxic, Fragrance-Free"},
    ],
    "Safety & Security": [
        {"name": "Type", "default_values": "Smoke Detectors, Security Cameras, Locks, Safes"},
        {"name": "Brand", "default_values": "Nest, Ring, Yale, Master Lock"},
        {"name": "Features", "default_values": "Wireless, Motion Detection, Waterproof, Fire-Resistant"},
        {"name": "Use", "default_values": "Home, Office, Outdoor, Personal"},
    ],
    "Home Appliances": [
        {"name": "Type", "default_values": "Refrigerators, Washing Machines, Ovens, Vacuums"},
        {"name": "Brand", "default_values": "Samsung, LG, Whirlpool, Dyson"},
        {"name": "Energy Efficiency", "default_values": "Energy Star, A+, A++, A+++"},
        {"name": "Features", "default_values": "Smart Technology, Stainless Steel, Compact, High Capacity"},
    ],
    "Barbecue & Outdoor Cooking": [
        {"name": "Type", "default_values": "Grills, Smokers, Pizza Ovens, Fire Pits"},
        {"name": "Fuel Type", "default_values": "Charcoal, Gas, Electric, Wood"},
        {"name": "Brand", "default_values": "Weber, Char-Broil, Traeger, Blackstone"},
        {"name": "Features", "default_values": "Portable, Built-in Thermometer, Side Burner, Rotisserie"},
    ],
    "Fitness Equipment": [
        {"name": "Type", "default_values": "Treadmills, Exercise Bikes, Ellipticals, Weight Benches"},
        {"name": "Brand", "default_values": "Bowflex, NordicTrack, Peloton, ProForm"},
        {"name": "Material", "default_values": "Steel, Plastic, Rubber, Foam"},
        {"name": "Features", "default_values": "Adjustable Resistance, Foldable, Digital Display, Heart Rate Monitor"},
    ],
    "Camping Gear": [
        {"name": "Type", "default_values": "Tents, Sleeping Bags, Camping Stoves, Lanterns"},
        {"name": "Brand", "default_values": "Coleman, REI, Marmot, MSR"},
        {"name": "Material", "default_values": "Nylon, Polyester, Aluminum, Stainless Steel"},
        {"name": "Features", "default_values": "Waterproof, Lightweight, Portable, Durable"},
    ],
    "Cycling": [
        {"name": "Type", "default_values": "Road Bikes, Mountain Bikes, Hybrid Bikes, Electric Bikes"},
        {"name": "Brand", "default_values": "Trek, Specialized, Cannondale, Giant"},
        {"name": "Material", "default_values": "Aluminum, Carbon Fiber, Steel, Titanium"},
        {"name": "Features", "default_values": "Suspension, Disc Brakes, Gears, Adjustable Seat"},
    ],
    "Fishing": [
        {"name": "Type", "default_values": "Rods, Reels, Lures, Fishing Lines"},
        {"name": "Brand", "default_values": "Shimano, Daiwa, Penn, Abu Garcia"},
        {"name": "Material", "default_values": "Graphite, Fiberglass, Stainless Steel, Plastic"},
        {"name": "Features", "default_values": "Corrosion Resistant, Lightweight, High Sensitivity, Smooth Drag"},
    ],
    "Hiking": [
        {"name": "Type", "default_values": "Backpacks, Hiking Boots, Trekking Poles, Navigation Tools"},
        {"name": "Brand", "default_values": "Osprey, Merrell, Black Diamond, Garmin"},
        {"name": "Material", "default_values": "Leather, Nylon, Aluminum, Rubber"},
        {"name": "Features", "default_values": "Waterproof, Breathable, Adjustable Straps, Shock Absorption"},
    ],
    "Skincare": [
        {"name": "Type", "default_values": "Moisturizers, Cleansers, Serums, Sunscreens"},
        {"name": "Brand", "default_values": "CeraVe, Neutrogena, The Ordinary, La Roche-Posay"},
        {"name": "Ingredients", "default_values": "Hyaluronic Acid, Retinol, Vitamin C, Niacinamide"},
        {"name": "Skin Type", "default_values": "Normal, Oily, Dry, Combination"},
    ],
    "Makeup": [
        {"name": "Type", "default_values": "Foundation, Mascara, Lipstick, Eyeshadow"},
        {"name": "Brand", "default_values": "Maybelline, L'Oréal, MAC, NARS"},
        {"name": "Finish", "default_values": "Matte, Glossy, Shimmer, Natural"},
        {"name": "Color Range", "default_values": "Wide, Limited, Diverse, Inclusive"},
    ],
    "Hair Care": [
        {"name": "Type", "default_values": "Shampoos, Conditioners, Hair Oils, Hair Masks"},
        {"name": "Brand", "default_values": "Pantene, Garnier, Moroccanoil, Olaplex"},
        {"name": "Hair Type", "default_values": "Curly, Straight, Wavy, Coily"},
        {"name": "Benefits", "default_values": "Moisturizing, Strengthening, Volumizing, Repairing"},
    ],
    "Fragrances": [
        {"name": "Type", "default_values": "Perfumes, Eau de Toilette, Cologne, Body Sprays"},
        {"name": "Brand", "default_values": "Chanel, Dior, Calvin Klein, Versace"},
        {"name": "Scent Type", "default_values": "Floral, Woody, Oriental, Fresh"},
        {"name": "Concentration", "default_values": "Parfum, Eau de Parfum, Eau de Toilette, Eau de Cologne"},
    ],
    "Personal Hygiene": [
        {"name": "Type", "default_values": "Toothpaste, Deodorant, Feminine Hygiene Products, Hand Sanitizers"},
        {"name": "Brand", "default_values": "Colgate, Dove, Always, Purell"},
        {"name": "Packaging", "default_values": "Tube, Stick, Pads, Gel"},
        {"name": "Features", "default_values": "Fluoride-Free, Aluminum-Free, Organic, Antibacterial"},
    ],
    "Action Figures": [
        {"name": "Type", "default_values": "Superheroes, Movie Characters, Anime Figures, Collectibles"},
        {"name": "Brand", "default_values": "Hasbro, Mattel, Bandai, Funko"},
        {"name": "Material", "default_values": "Plastic, Vinyl, Resin, Metal"},
        {"name": "Features", "default_values": "Articulated, Limited Edition, Light-Up, Sound Effects"},
    ],
    "Board Games": [
        {"name": "Type", "default_values": "Strategy, Family, Party, Cooperative"},
        {"name": "Brand", "default_values": "Catan, Monopoly, Ticket to Ride, Pandemic"},
        {"name": "Age Range", "default_values": "Kids, Teens, Adults, All Ages"},
        {"name": "Number of Players", "default_values": "2-4, 2-6, 1-8, 2-10"},
    ],
    "Dolls": [
        {"name": "Type", "default_values": "Fashion Dolls, Baby Dolls, Collectible Dolls, Interactive Dolls"},
        {"name": "Brand", "default_values": "Barbie, American Girl, L.O.L. Surprise!, Disney"},
        {"name": "Material", "default_values": "Plastic, Fabric, Silicone, Vinyl"},
        {"name": "Features", "default_values": "Changeable Outfits, Hair Styling, Sound Effects, Movement"},
    ],
    "Puzzles": [
        {"name": "Type", "default_values": "Jigsaw Puzzles, Brain Teasers, 3D Puzzles, Crossword Puzzles"},
        {"name": "Brand", "default_values": "Ravensburger, Buffalo Games, White Mountain, Clementoni"},
        {"name": "Difficulty", "default_values": "Easy, Medium, Hard, Expert"},
        {"name": "Pieces", "default_values": "100-500, 500-1000, 1000-2000, 2000+"},
    ],
    "Outdoor Toys": [
        {"name": "Type", "default_values": "Bounce Houses, Swing Sets, Water Slides, Trampolines"},
        {"name": "Brand", "default_values": "Little Tikes, Step2, Intex, Skywalker"},
        {"name": "Material", "default_values": "Plastic, Metal, Fabric, Rubber"},
        {"name": "Age Range", "default_values": "Toddlers, Preschoolers, School-Age, Teens"},
    ],
    "Fiction Books": [
        {"name": "Genre", "default_values": "Mystery, Romance, Fantasy, Science Fiction"},
        {"name": "Author", "default_values": "Stephen King, J.K. Rowling, Agatha Christie, George R.R. Martin"},
        {"name": "Format", "default_values": "Hardcover, Paperback, Audiobook, eBook"},
        {"name": "Language", "default_values": "English, Spanish, French, German"},
    ],
    "Non-Fiction Books": [
        {"name": "Category", "default_values": "Biography, History, Self-Help, Cookbooks"},
        {"name": "Author", "default_values": "Michelle Obama, Yuval Noah Harari, Brené Brown, Jamie Oliver"},
        {"name": "Format", "default_values": "Hardcover, Paperback, Audiobook, eBook"},
        {"name": "Language", "default_values": "English, Spanish, French, German"},
    ],
    "Children's Books": [
        {"name": "Age Range", "default_values": "0-2, 3-5, 6-8, 9-12"},
        {"name": "Genre", "default_values": "Picture Books, Early Readers, Chapter Books, Middle Grade"},
        {"name": "Author", "default_values": "Dr. Seuss, Eric Carle, Roald Dahl, J.K. Rowling"},
        {"name": "Features", "default_values": "Illustrated, Interactive, Educational, Award-Winning"},
    ],
    "Notebooks": [
        {"name": "Type", "default_values": "Spiral, Composition, Legal Pad, Journal"},
        {"name": "Size", "default_values": "A4, A5, A6, B5"},
        {"name": "Binding", "default_values": "Wire-Bound, Perfect Bound, Stapled, Thread-Bound"},
        {"name": "Paper Type", "default_values": "Lined, Grid, Dotted, Blank"},
    ],
    "Writing Instruments": [
        {"name": "Type", "default_values": "Pens, Pencils, Markers, Highlighters"},
        {"name": "Brand", "default_values": "Pilot, BIC, Sharpie, Staedtler"},
        {"name": "Ink Type", "default_values": "Ballpoint, Gel, Fountain, Rollerball"},
        {"name": "Material", "default_values": "Plastic, Metal, Wood, Rubber"},
    ],
    "Snacks": [
        {"name": "Type", "default_values": "Chips, Crackers, Nuts, Popcorn"},
        {"name": "Brand", "default_values": "Lay's, Nabisco, Planters, Orville Redenbacher's"},
        {"name": "Flavor", "default_values": "Salty, Sweet, Spicy, Savory"},
        {"name": "Dietary Preferences", "default_values": "Gluten-Free, Organic, Vegan, Low Calorie"},
    ],
    "Beverages": [
        {"name": "Type", "default_values": "Soft Drinks, Juices, Water, Coffee"},
        {"name": "Brand", "default_values": "Coca-Cola, Tropicana, Dasani, Starbucks"},
        {"name": "Flavor", "default_values": "Cola, Orange, Lemon-Lime, Mocha"},
        {"name": "Packaging", "default_values": "Bottle, Can, Box, Pouch"},
    ],
    "Gourmet Foods": [
        {"name": "Type", "default_values": "Cheese, Chocolate, Olive Oil, Truffles"},
        {"name": "Brand", "default_values": "Godiva, Lindt, Bertolli, Urbani"},
        {"name": "Origin", "default_values": "Italy, France, Belgium, Spain"},
        {"name": "Dietary Preferences", "default_values": "Organic, Gluten-Free, Vegan, Kosher"},
    ],
    "Health Foods": [
        {"name": "Type", "default_values": "Superfoods, Protein Bars, Supplements, Herbal Teas"},
        {"name": "Brand", "default_values": "Navitas Organics, Clif Bar, Optimum Nutrition, Yogi Tea"},
        {"name": "Benefits", "default_values": "Energy Boosting, Weight Management, Immune Support, Detox"},
        {"name": "Dietary Preferences", "default_values": "Organic, Gluten-Free, Vegan, Non-GMO"},
    ],
    "Canned & Packaged Foods": [
        {"name": "Type", "default_values": "Soups, Canned Vegetables, Canned Fruits, Packaged Meals"},
        {"name": "Brand", "default_values": "Campbell's, Green Giant, Del Monte, Kraft"},
        {"name": "Shelf Life", "default_values": "Long Shelf Life, Ready to Eat, Easy to Prepare, Microwaveable"},
        {"name": "Dietary Preferences", "default_values": "Low Sodium, Organic, Vegan, Gluten-Free"},
    ],
    "Vitamins & Supplements": [
        {"name": "Type", "default_values": "Multivitamins, Probiotics, Omega-3, Vitamin D"},
        {"name": "Brand", "default_values": "Centrum, Culturelle, Nordic Naturals, Nature Made"},
        {"name": "Form", "default_values": "Tablets, Capsules, Gummies, Liquids"},
        {"name": "Purpose", "default_values": "General Health, Digestive Health, Heart Health, Bone Health"},
    ],
    "Personal Care": [
        {"name": "Type", "default_values": "Body Wash, Shampoo, Toothpaste, Deodorant"},
        {"name": "Brand", "default_values": "Dove, Pantene, Colgate, Old Spice"},
        {"name": "Ingredients", "default_values": "Natural, Paraben-Free, Sulfate-Free, Alcohol-Free"},
        {"name": "Benefits", "default_values": "Moisturizing, Strengthening, Whitening, Odor Protection"},
    ],
    "Fitness & Nutrition": [
        {"name": "Type", "default_values": "Protein Powders, Energy Bars, Hydration, Pre-Workout Supplements"},
        {"name": "Brand", "default_values": "Optimum Nutrition, Clif Bar, Gatorade, Cellucor"},
        {"name": "Flavor", "default_values": "Chocolate, Vanilla, Strawberry, Lemon"},
        {"name": "Dietary Preferences", "default_values": "Gluten-Free, Vegan, Low Sugar, Keto-Friendly"},
    ],
    "Medical Supplies": [
        {"name": "Type", "default_values": "First Aid Kits, Bandages, Thermometers, Blood Pressure Monitors"},
        {"name": "Brand", "default_values": "Band-Aid, 3M, Braun, Omron"},
        {"name": "Purpose", "default_values": "Wound Care, Fever Monitoring, Blood Pressure Management, Pain Relief"},
        {"name": "Features", "default_values": "Sterile, Easy to Use, Accurate, Portable"},
    ],
    "Wellness Devices": [
        {"name": "Type", "default_values": "Massagers, Air Purifiers, Humidifiers, Light Therapy Devices"},
        {"name": "Brand", "default_values": "HoMedics, Dyson, Honeywell, Philips"},
        {"name": "Purpose", "default_values": "Relaxation, Air Quality, Humidity Control, Mood Enhancement"},
        {"name": "Features", "default_values": "Portable, Quiet Operation, Adjustable Settings, Energy Efficient"},
    ],
    "Car Accessories": [
        {"name": "Type", "default_values": "Seat Covers, Floor Mats, Dash Cams, Car Chargers"},
        {"name": "Brand", "default_values": "Coverking, WeatherTech, Garmin, Anker"},
        {"name": "Material", "default_values": "Leather, Rubber, Plastic, Fabric"},
        {"name": "Features", "default_values": "Durable, Easy to Clean, High Definition, Fast Charging"},
    ],
    "Car Electronics": [
        {"name": "Type", "default_values": "Car Stereos, GPS Navigation, Backup Cameras, Car Alarms"},
        {"name": "Brand", "default_values": "Pioneer, Garmin, YI, Viper"},
        {"name": "Features", "default_values": "Bluetooth, Touchscreen, Voice Control, Remote Start"},
        {"name": "Compatibility", "default_values": "Universal, Specific Models, Android, iOS"},
    ],
    "Car Care": [
        {"name": "Type", "default_values": "Car Wash, Wax, Interior Cleaners, Tire Shine"},
        {"name": "Brand", "default_values": "Meguiar's, Chemical Guys, Armor All, Turtle Wax"},
        {"name": "Purpose", "default_values": "Cleaning, Protection, Shine, Odor Elimination"},
        {"name": "Features", "default_values": "Biodegradable, UV Protection, Non-Greasy, Long-Lasting"},
    ],
    "Motorcycle Parts": [
        {"name": "Type", "default_values": "Helmets, Exhausts, Tires, Batteries"},
        {"name": "Brand", "default_values": "Shoei, Akrapovic, Michelin, Yuasa"},
        {"name": "Material", "default_values": "Carbon Fiber, Stainless Steel, Rubber, Lead Acid"},
        {"name": "Features", "default_values": "DOT Approved, High Performance, Durable, Maintenance-Free"},
    ],
    "Tires & Wheels": [
        {"name": "Type", "default_values": "All-Season Tires, Performance Tires, Alloy Wheels, Steel Wheels"},
        {"name": "Brand", "default_values": "Michelin, Goodyear, BBS, Enkei"},
        {"name": "Size", "default_values": "16 inch, 17 inch, 18 inch, 20 inch"},
        {"name": "Features", "default_values": "Fuel Efficient, Wet Traction, Lightweight, Corrosion Resistant"},
    ],

}

