# Generated by Django 4.2.8 on 2024-01-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_sellerprofile_paymentinfo_identificationdocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="is_verified_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="store_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="SellerContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("citizenship_country", models.CharField(max_length=100)),
                ("birth_country", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("residential_country", models.CharField(max_length=100)),
                ("contact_person_role", models.CharField(max_length=50)),
                ("address_line1", models.CharField(max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_people",
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
