# Generated by Django 4.2.8 on 2024-01-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_sellerprofile_is_verified_seller_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="is_verified_seller",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_verified_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="identificationdocument",
            name="document_type",
            field=models.CharField(blank=True, default="tax_id", max_length=50),
        ),
    ]
