# Generated by Django 4.2.8 on 2024-01-22 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_sellerprofile_is_verified_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
