# Generated by Django 4.2.8 on 2024-01-22 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_sellerprofile_created_sellerprofile_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
