# Generated by Django 4.2.8 on 2024-02-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_address_address_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="available_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="on_hold_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="ShippingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CR", "Credit"), ("DR", "Debit")], max_length=2
                    ),
                ),
                ("courier_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "courier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_transactions",
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CR", "Credit"), ("DR", "Debit")], max_length=2
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="users.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
