# Generated by Django 4.2.8 on 2024-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_sellerprofile_available_balance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sellertransaction",
            old_name="order_id",
            new_name="reference_id",
        ),
        migrations.AddField(
            model_name="sellertransaction",
            name="closing_balance",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
