# Generated by Django 4.2.8 on 2024-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_order_id_sellertransaction_reference_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellertransaction",
            name="variation",
            field=models.CharField(
                choices=[("ITEM_BOUGHT", "Item bought"), ("WITHDRAW", "Withdraw")],
                default="ITEM_BOUGHT",
                max_length=50,
            ),
        ),
    ]
