# Generated by Django 4.2.8 on 2024-03-22 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_sellertransaction_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="square_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_id", models.CharField(max_length=255)),
                ("bin_number", models.CharField(max_length=255)),
                ("card_brand", models.CharField(max_length=255)),
                ("card_type", models.CharField(max_length=255)),
                ("cardholder_name", models.CharField(max_length=255)),
                ("last_4", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
