# Generated by Django 4.2.8 on 2024-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_useraccount_square_customer_id_usercard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="sellerprofile",
            options={"verbose_name": "Seller", "verbose_name_plural": "Sellers"},
        ),
        migrations.DeleteModel(
            name="PaymentInfo",
        ),
    ]
