# Generated by Django 4.2.8 on 2024-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_address_options_alter_sellerprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellertransaction",
            name="variation",
            field=models.CharField(
                choices=[
                    ("ITEM_BOUGHT", "Item bought"),
                    ("WITHDRAW", "Withdraw"),
                    ("UNHOLD_MONEY", "Money available"),
                ],
                default="ITEM_BOUGHT",
                max_length=50,
            ),
        ),
    ]
