# Generated by Django 4.2.8 on 2024-03-30 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_withdrawrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="identificationdocument",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterModelOptions(
            name="sellercontactperson",
            options={
                "verbose_name": "Contact person",
                "verbose_name_plural": "Contact people",
            },
        ),
        migrations.AlterModelOptions(
            name="sellertransaction",
            options={
                "verbose_name": "Seller transaction",
                "verbose_name_plural": "Seller transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="shippingtransaction",
            options={
                "verbose_name": "Shipping transaction",
                "verbose_name_plural": "Shipping transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="useraccount",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="usercard",
            options={"verbose_name": "Card", "verbose_name_plural": "Cards"},
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line1",
            field=models.CharField(max_length=255, verbose_name="Address line 1"),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address line 2"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=100, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Zip code"),
        ),
        migrations.AlterField(
            model_name="identificationdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                default="tax_id",
                max_length=50,
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="identificationdocument",
            name="file",
            field=models.FileField(upload_to="documents/", verbose_name="Document"),
        ),
        migrations.AlterField(
            model_name="identificationdocument",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="identificationdocument",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Upload date"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="address_line1",
            field=models.CharField(max_length=255, verbose_name="Address line 1"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address line 2"
            ),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="birth_country",
            field=models.CharField(max_length=100, verbose_name="Birth country"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="birth_date",
            field=models.DateField(verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="citizenship_country",
            field=models.CharField(max_length=100, verbose_name="Citizenship"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="contact_person_role",
            field=models.CharField(max_length=50, verbose_name="Contact person role"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="residential_country",
            field=models.CharField(max_length=100, verbose_name="Residential country"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_people",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="state",
            field=models.CharField(max_length=100, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="sellercontactperson",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Zip code"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="address_line1",
            field=models.CharField(max_length=255, verbose_name="Address line 1"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="address_line2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address line 2"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="available_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Available balance",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="Business name"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_type",
            field=models.CharField(max_length=100, verbose_name="Business type"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="custom_business_type",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Custom business type",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="is_agreement_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Is agreement accepted"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="Is phone verified"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="on_hold_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="On hold balance",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="phone_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="state",
            field=models.CharField(max_length=100, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="store_name",
            field=models.CharField(max_length=255, verbose_name="Store name"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="zip_code",
            field=models.CharField(max_length=20, verbose_name="Zip code"),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="closing_balance",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Closing balance"
            ),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="reference_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Reference ID"
            ),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("CR", "Credit"), ("DR", "Debit")],
                max_length=2,
                verbose_name="Transaction type",
            ),
        ),
        migrations.AlterField(
            model_name="sellertransaction",
            name="variation",
            field=models.CharField(
                choices=[
                    ("ITEM_BOUGHT", "Item bought"),
                    ("WITHDRAW", "Withdraw"),
                    ("UNHOLD_MONEY", "Money available"),
                ],
                default="ITEM_BOUGHT",
                max_length=50,
                verbose_name="Variation",
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount ($)"
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="courier_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Courier ID"
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="courier_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Courier name"
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="order_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Order ID"
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_transactions",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
        ),
        migrations.AlterField(
            model_name="shippingtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("CR", "Credit"), ("DR", "Debit")],
                max_length=2,
                verbose_name="Transaction type",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_seller",
            field=models.BooleanField(default=False, verbose_name="Is seller"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is staff"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Is superuser"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_verified_seller",
            field=models.BooleanField(default=False, verbose_name="Is verified seller"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="square_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Square customer id"
            ),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="bin_number",
            field=models.CharField(max_length=255, verbose_name="Bin number"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="card_brand",
            field=models.CharField(max_length=255, verbose_name="Card brand"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="card_type",
            field=models.CharField(max_length=255, verbose_name="Card type"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="cardholder_name",
            field=models.CharField(max_length=255, verbose_name="Cardholder name"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="last_4",
            field=models.CharField(max_length=255, verbose_name="Last 4 digits"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="reference_id",
            field=models.CharField(max_length=255, verbose_name="Square id"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount ($)"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="bin_number",
            field=models.CharField(max_length=255, verbose_name="Bin number"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="card_brand",
            field=models.CharField(max_length=255, verbose_name="Card brand"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="card_type",
            field=models.CharField(max_length=255, verbose_name="Card type"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="cardholder_name",
            field=models.CharField(max_length=255, verbose_name="Cardholder name"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Fee amount ($)"
            ),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="last_4",
            field=models.CharField(max_length=255, verbose_name="Last 4 digits"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="reference_id",
            field=models.CharField(max_length=255, verbose_name="Reference ID"),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdraw_requests",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("PROCESSING", "Processing"),
                    ("FAILED", "Failed"),
                ],
                default="PROCESSING",
                max_length=50,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawrequest",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
        ),
    ]
