# Generated by Django 4.2.8 on 2024-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_identificationdocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("PROCESSING", "Processing"),
                    ("FAILED", "Failed"),
                ],
                default="PROCESSING",
                max_length=50,
                verbose_name="State of process",
            ),
        ),
    ]
